version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_nestjs_study
    # restart: always
    environment:
      POSTGRES_DB: study_nestjs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: